summary: test squid starts and connects (ipv4)

execute: |

  # Cilium (CNI) is not yet supported on s390x and ppc64le
  # so we'll skip the k8s tests on those architectures for now
  # ---
  # TODO: Remove this check once Cilium supports s390x and ppc64le
  if [ "$(uname -m)" = "s390x" ] || [ "$(uname -m)" = "ppc64le" ]; then
    echo "Skipping k8s tests on $(uname -m) architecture"
    exit 0
  fi

  # Create the configmap with the squid.conf file
  k8s kubectl create configmap squid-config --from-file=squid=squid.conf

  # Start the squid container
  k8s kubectl apply -f deployment.yaml
  k8s kubectl rollout status deploy/squid-deployment --timeout=120s

  # Wait for the setup to be ready
  timeout 30 bash -c 'until curl -s -x http://127.0.0.1:30128 https://ubuntu.com >/dev/null; do sleep 1; done'

  # Test that squid can connect to the web server (ipv4)
  curl -4 -s -o /dev/null -w '%{http_code}' -x http://127.0.0.1:30128 https://ubuntu.com | grep -qF "200"
  k8s kubectl exec deploy/squid-deployment -- cat /var/log/squid/access.log | grep -qF "CONNECT ubuntu.com:443"
